apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app
  labels:
    app: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
      - name: ping-pong-app
        image: paulajuliabalza/ping-pong:1.9.1
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
